### PR TITLE
Pull translations (connect #589)

### PR DESCRIPTION
**Pull request by valllllll2000**
#### Before the PR (what is the issue or what needed to be done)
Some translations missing
#### The solution
Did some translations and pulled the ones available
#### Screenshots (if appropriate)
NA
#### Reviewer Checklist
* [ ] Connect the issue
* [ ] Test plan
* [ ] Copyright header
* [ ] Code formatting
* [ ] Documentation

### CODE REVIEW

**Comment by valllllll2000** [comment]
@nhternup Good catch, I have fixed this!

**Comment by valllllll2000** [comment]
@nhternup I cannot do that because I do not understand those languages at all, I know for sure that Portuguese, Spanish and French everything is correct. If you know some of the other languages, feel free to change it in Transifex and let me know so I pull it again.

**Comment by valllllll2000** [comment]
@nhternup It should all be fixed now

**Comment by nhternup** [comment]
@valllllll2000 nicely fixed
There are some places where just the word 'Flow' is used. We could maybe correct this to 'Akvo Flow'

**Pull request merged**
